### ISSUE TITLE
Looping Sound Error

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#1] opened 2018-10-13 00:49 UTC
Sounds appear to get "stuck," looping until the mod is removed and the world is loaded. May possibly be fixed by reloading the client, although one of two reports seemed to say that did not help. Here's a log. It's mostly the sound error looping.
https://www.dropbox.com/s/fejxf8iplrx4nab/latest.log?raw=1

**Comment by obsidian29** [comment] 2018-10-13 00:52
Reloading the resource manager fixed it for me.

**Comment by DonBruce64** [comment] 2018-10-13 00:53
Something in the code is causing the SoundSystem to keep playing the sound.  I'm not sure what, but re-loading the Resources (F3+B) does indeed restart the SoundSystem, so it makes sense that would kill the looping sound.  Good to know there's a quick-fix if players encounter it.

When exactly does the sound get stuck?  Is it randomly, or during a specific action?

**Comment by obsidian29** [comment] 2018-10-13 00:55
All I know is that I was flying in and out of the area, it could have unloaded, and the engine running in the Scout. It seemed to get stuck while I was revving the engine and playing with the gearshift though.

**Comment by DonBruce64** [comment] 2018-10-18 02:03
When this sound got stuck, were you in the vehicle the sound was playing on?  Like, did it get stuck when you were in the same area as that vehicle?  Trying to figure out if the issue is with the vehicle unloading or something else.

**Comment by molletts** [comment] 2018-11-17 21:17
I've also experienced this issue (at least, I assume it's the same issue, not another one that has similar symptoms), while flying. The aircraft's engine sound gets stuck, although I can still hear the "live" engine sound, which responds to throttle changes, in addition to the "looping" one, which doesn't. (I actually had three "stuck" sounds playing on one occasion.)

It seems more likely to happen when the game is struggling to keep up, for example, if I stray too close to the edge of the known world and new terrain starts being generated. Steep turns also sometimes cause it, although in MTS v12, which feels much smoother, I haven't yet been able to trigger it this way despite throwing the MC-172 around quite enthusiastically.

Exiting to the main menu does not stop the sound - it will continue playing until the game client is closed. In v12, it is possible to re-enter the game from the menu, with the sound still playing. When I attempted this with v11, a Forge server state error occurred.

**Comment by MrSmith3101** [comment] 2019-04-19 19:30
I'm also affected by this bug using "Immersive Vehicles-1.12.2-13.1.0.jar"
It behaves exactly the same as described by the user "molletts" previously.

It does occur very often so playing with this mod is currently not possible for me. I will answer any question if it helps fixing this bug.

KR,
Patrick

**Comment by DonBruce64** [comment] 2019-05-06 03:23
Addressed in V14.2.0.  Should *hopefully* not occur anymore.  Initial testing was successful in removing the phantom sounds.

**Closed by DonBruce64** 2019-05-06 03:23 UTC
Labels: bug
