### ISSUE TITLE
Pole Bug

### ISSUE THREAD

**Issue by SlikeSnake1** [DonBruce64/MinecraftTransportSimulator#1575] opened 2023-03-21 15:46 UTC
Hey,

When I place the Pole it's completely buggy and I can't use signs or the traffic lights on it.

Can you fix it? Or what is the problem? 

 

Image of the Bug: https://ibb.co/fQKb3D8

**Comment by DonBruce64** [comment] 2023-03-22 21:08
Duplicate of #1537

**Closed by DonBruce64** 2023-03-22 21:08 UTC
Labels: bug, duplicate
