### ISSUE TITLE
Vehicles dont show in OCP 1.16.5

### ISSUE THREAD

**Issue by Ocelotko123** [DonBruce64/MinecraftTransportSimulator#1838] opened 2024-08-19 14:26 UTC
I started the game and I cant see the vehicles in the OCP tab.
![2024-08-19_16 18 14](https://github.com/user-attachments/assets/a58dcc18-7790-48fe-97d3-3e0eedd21ff8)
![2024-08-19_16 18 22](https://github.com/user-attachments/assets/79585a08-f4c2-4bd6-aebe-d598c061cd5c)
![2024-08-19_16 18 27](https://github.com/user-attachments/assets/2054bdff-63a6-461a-9e34-93e35c5abdc1)
![2024-08-19_16 18 33](https://github.com/user-attachments/assets/d443aa17-0478-4fb4-81d5-9537f46bcb7b)

**Comment by DonBruce64** [comment] 2024-08-27 23:09
Duplicate of #1834 .  Please post information there.

**Closed by DonBruce64** 2024-08-27 23:09 UTC
Labels: bug, duplicate, packard
