### ISSUE TITLE
Multiplayer problem

### ISSUE THREAD

**Issue by NoweR-c** [DonBruce64/MinecraftTransportSimulator#364] opened 2020-03-24 16:10 UTC
I discovered a multiplayer problem. I run this mod on Aternos among with trim vehicle pack and UNU vehicle pack and if I'm driving a car and a player in the same chunk as me doesn't drive a car, that player can control my car.

For example, if i'm in a car with a player nearby and I am on drive and I'm driving straight and that player presses D, my car will turn left even if I press D or not.

**Comment by DonBruce64** [comment] 2020-03-24 20:24
This is a duplicate of #354.  Update your version of MTS to the most recent (V17.3.1) and the error will go away.

**Closed by DonBruce64** 2020-03-24 20:24 UTC
Labels: bug, duplicate
