### ISSUE TITLE
crash when entering vehicle on server

### ISSUE THREAD

**Issue by cpufreak** [DonBruce64/MinecraftTransportSimulator#366] opened 2020-03-26 00:28 UTC
it's with the corvair van. we just got it built, went to sit in it, and instantly disconnects with "a fatal error has occurred" message. server log attached as nothing shows up in the client log.
[message (2).txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4384367/message.2.txt)

**Comment by JustSupernova** [comment] 2020-03-26 01:27
Same here it does exacly the same if i try and add gages or indicator.
Tested with other cars and planes as im admin on the server same thing.

**Comment by DonBruce64** [comment] 2020-03-26 05:36
Literally a ticket was submitted earlier today (#365) for this issue, which was a duplicate of another ticket,which was an issue that was already addressed.   Folks, you need to check Curse for updates before you submit bug reports for issues that have already been addressed!

**Closed by DonBruce64** 2020-03-26 05:36 UTC
Labels: duplicate
