### ISSUE TITLE
Jittering while turning

### ISSUE THREAD

**Issue by DonPearl-TCGAD** [DonBruce64/MinecraftTransportSimulator#196] opened 2019-10-09 16:52 UTC
Well, this comes about as I'm using the latest IV/MTS version. When I noticed this while making a road for a map of my and testing it

I'm not sure anyone else is having this issue but I did restart my client

**Comment by DonPearl-TCGAD** [comment] 2019-10-10 02:43
This report is as of 15.2.0

**Comment by DonBruce64** [comment] 2019-10-17 01:45
This is directly caused by this change:
2ffd6a53745cd8a663eae8b1c898bce5eb5756d6

I can fix this, but it'll likely cause more jittering in other cases.  Pick your poison....

**Comment by DonBruce64** [comment] 2019-11-08 02:54
Fixed in V15.5.0.

**Closed by DonBruce64** 2019-11-08 02:54 UTC
Labels: bug
