### ISSUE TITLE
Cannot install any propellers on fixed-wing propeller aircraft

### ISSUE THREAD

**Issue by Jiefang3113** [DonBruce64/MinecraftTransportSimulator#1812] opened 2024-07-04 06:58 UTC
Versions: 1.16.5 and 1.12.2
Mod version: V22.15.0  Mod content Pack: MTS Official Content Pack V25
Description: After installing the engine, I held the proper propeller and right-clicked the green hologram, but nothing happened
Tried on each fixed-wing propellers aircraft and each propeller in the content pack, got the same result
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/148638116/4b2962c1-ee75-4d09-acfb-25701442ebb6)
No such phenomenon on helicopters
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/148638116/1612688d-970b-4152-bbc3-a0e732d2da89)

**Comment by CSdiscoveries** [comment] 2024-07-05 02:31
It's possible, if you really spend a lot of time trying to place the propeller in seemingly random spots. However it is still extremely difficult to place propellers, and very clearly seems to be an issue.

**Comment by DonBruce64** [comment] 2024-07-16 20:37
I could of swore I made this not be a thing in the release as I saw this.  You're running the Curse file, not a beta, right?

**Comment by CSdiscoveries** [comment] 2024-07-16 20:53
Correct. On some planes like the Comanche, it can be as simple as digging down a single block and right-clicking while looking 180 degrees from the intended click area. On other planes such as the MC-172, it's nigh impossible to place a propeller, and as of yet I have not found a way to make it work.

**Comment by DonBruce64** [comment] 2024-07-16 21:03
Yeah, root cause is the fact I made the holo-boxes smaller since for most parts it was getting cluttered.  But I remember for sure making propeller boxes larger specifically because I saw this happen during testing.

**Comment by Jiefang3113** [comment] 2024-07-22 15:32
> I could of swore I made this not be a thing in the release as I saw this. You're running the Curse file, not a beta, right?

Yes, I'm running on the Curse file.
It seemed that older version of mod have worked well both on 1.12 and 1.16, but newer were neither worked on both versions.

**Comment by DonBruce64** [comment] 2024-07-22 15:36
So, I found I made the fix, but didn't make it properly.  Beta is on Discord if you want to use it.

**Comment by DonBruce64** [comment] 2024-08-05 04:13
Addressed in 22.16.0.

**Closed by DonBruce64** 2024-08-05 04:13 UTC
Labels: bug
