### ISSUE TITLE
It is impossible to continue playing on the server when exiting the transport (1.16.5)

### ISSUE THREAD

**Issue by FireWolfFW** [DonBruce64/MinecraftTransportSimulator#1771] opened 2024-02-05 06:13 UTC
If you exit the vehicle (no matter which one), the screen will lock in one position and will not allow you to move from your place
The commands will also not work
The only thing that can help is:
1. Log in to the server (sometimes the game thinks that someone is still sitting in the driver's seat)
2. The /kill command in the server console, since self-input is useless

https://cursefire.com/minecraft/mc-mods/minecraft-transport-simulator/issues/1666

**Comment by DonBruce64** [comment] 2024-02-05 13:47
This is a duplicate of #1750.  I see you're on the Discord, so I'll grab details from you there.

**Closed by DonBruce64** 2024-02-05 13:47 UTC
Labels: bug, duplicate
