### ISSUE TITLE
Planes can't take off

### ISSUE THREAD

**Issue by Tzhu14** [DonBruce64/MinecraftTransportSimulator#1162] opened 2022-04-14 09:42 UTC
I meet the problem that all the planes are stuck on the ground and cannot go up even I press the ThrottleUp key after accelerating to about 60 blocks per second. I watched some online videos, and see that the back half of the planes may leave the ground when the speed is enough to take off, but this never happen in my MC——the planes perform like cars here. My MC version is 1.12, and the mod version is 21.1.0 which released on Mar 20, 2022 referring to Curseforge. Also, I meet the bug of the Speedometers which discussed by many other people. I wonder whether there is a connection between these two problems, for instance, the mod think my speed is only 7 blocks per second even I have reached a very high speed that is enough to take off？

Anyway, I appreciate your works and hope that your mod will be more and more wonderful!

**Comment by DonBruce64** [comment] 2022-04-14 12:12
Duplicate of #1156

**Closed by DonBruce64** 2022-04-14 12:12 UTC
Labels: bug, duplicate
