### ISSUE TITLE
Part slot not rotate with part

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1175] opened 2022-04-23 01:28 UTC
![image](https://user-images.githubusercontent.com/79125581/164858966-28dd0e1e-8021-4046-b612-c85a69d3500d.png)
in this image the engine was transverse (rotated 90 degree) but the part slot still align in straight line as original part without rotation does

**Comment by DonBruce64** [comment] 2022-07-06 05:37
Marking as a dupe of #1173, though that one was classified wrongly given the true issue.

**Closed by DonBruce64** 2022-07-06 05:37 UTC
Labels: bug, duplicate, overhaul
