### ISSUE TITLE
Controller Issues

### ISSUE THREAD

**Issue by Yellowstrawberrys** [DonBruce64/MinecraftTransportSimulator#1043] opened 2022-01-07 09:35 UTC
I'm using Logitech X56 and G29 Controller,
 and when I try to click that controller then it crash with 
this message
▽▽
"The game crashed whilst rendering screen
Error: java.lang.ArrayIndexOutOfBoundsException: -14
Exit Code: -1"

crash report
[crash-2022-01-07_10.24.10-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7827912/crash-2022-01-07_10.24.10-client.txt)

**Comment by DonBruce64** [comment] 2022-01-08 01:13
Would I be able to get you to join the discord to test this with some beta builds?  That error *should* have gone away this latest version...

**Comment by DonBruce64** [comment] 2022-01-08 01:46
Also, just realized this is a duplicate of #1033, so I'm going to close this ticket and keep the results in the other one.

**Closed by DonBruce64** 2022-01-08 01:46 UTC
Labels: bug, duplicate
