### ISSUE TITLE
Bug with removing engine that breaks the whole engine system

### ISSUE THREAD

**Issue by MrRedstoneA1** [DonBruce64/MinecraftTransportSimulator#620] opened 2020-11-21 11:43 UTC
I tried removing a damaged engine from a plane. I had forgotten to turn off navigation lights and mag start. The engine would not drop, it stayed firmly in place. I turned navigation lights off but the mag start would not turn off. I decided to try picking the vehicle up and place it back down. Now the engine was gone and I put a new one in its place. I tried to start the new engine, but it would not start. The plane did not respond to the start button at all. Mag start was on.

Packs used:
Immersive Vehicles V18.5.0
Diamond Warriors Team IV pack V2.0.1
MTS Official Vehicle Pack V16.0.0
Plane used was Voltere VT-20 (factory primer) with DWT parts and MTS Official Pack gauges.

Steps to reproduce:
1. Assemble the VT-20 with parts from the DWT pack and MTS gauges. Fill the plane with fuel.
2. Turn nav lights and mag start both ON.
3. Remove the propeller. Try hitting the engine with the wrench. I used F3+B to see the hitbox.
4. After trying to remove the engine try turning nav lights and mag start OFF. Mag start will not turn OFF.
5. Pick up the vehicle and place it back down. The engine should be gone now.
6. Place the new engine in and try starting it. The plane should still have plenty of fuel. The engine won't start. The mag start button appears to be glitched and won't push down.
7. Get rid of the plane completely and make a new one. The new plane works fine.

Let me know if you need any additional info. Thanks!

**Comment by DonBruce64** [comment] 2020-11-21 17:39
Can you try to reproduce this in V19.9.0?  V18.5.0 is long-since obsolete and has a lot of quirks that were fixed in the various V19 builds.

**Comment by MrRedstoneA1** [comment] 2020-11-21 18:55
Seems to be fixed in V19 so no worries. Tested on multiple planes and did not cause any issues.

**Comment by DonBruce64** [comment] 2020-11-21 19:02
Awesome.  I recall there being an issue with hitscan detection on V18.5 where you'd end up "wrenching" multiple parts at the same click, but MTS would get confused.  But I don't think it was a documented issue, which is why I wasn't sure if this was the same or not.  Glad to see whatever it was it's gone.

**Closed by DonBruce64** 2020-11-21 19:02 UTC
Labels: bug, duplicate
