### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by LeSeltsam** [DonBruce64/MinecraftTransportSimulator#1103] opened 2022-02-24 17:42 UTC
Hi, i am having this text display issue in all MTS menus.
![image](https://user-images.githubusercontent.com/100374562/155578350-82150cc3-55e4-43ce-9232-788677425267.png)

**Comment by DonBruce64** [comment] 2022-02-25 01:40
Duplicate of #1048

**Closed by DonBruce64** 2022-02-25 01:40 UTC
Labels: bug, duplicate
