### ISSUE TITLE
[Bug] Beacons missing text fields

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1524] opened 2023-01-29 03:42 UTC
no text field = no working beacon

**Comment by gyrohero** [comment] 2023-02-09 21:28
It looks like the issue is in GUITextEditor.java.

LegacyCompatSystem.java adds fields for name, glideslope, and bearing to the beacon's definition. However, I don't see anywhere in GUITextEditor.java (which deals with creating GUIs for things like signs and beacons) where a beacon's definition would be referenced in order to add those fields to the GUI.

**Comment by DonBruce64** [comment] 2023-03-22 22:07
Fixed in V22.7.0.

**Closed by DonBruce64** 2023-03-22 22:07 UTC
Labels: bug

**Comment by CSdiscoveries** [comment] 2024-07-05 16:45
Having the same issue

**Comment by DonBruce64** [comment] 2024-07-16 21:08
Now how might you be having this issue when you can't open the beacon GUI via #1814 ?

**Comment by CSdiscoveries** [comment] 2024-07-16 21:30
that... is the issue. There's no text field, no HUD, nothing.
