### ISSUE TITLE
Crash when adding tracks to a vehicle

### ISSUE THREAD

**Issue by Fred-IGT** [DonBruce64/MinecraftTransportSimulator#260] opened 2020-01-12 17:15 UTC
We are seeing a consistent game crash when we put tracks onto a truck.

Here is a description of the vehicle from our 5-year-old debugging lead, Fred:

>Holds 16 cargo, has seats facing both ways, needs a truck engine, and caterpillar tracks make it move. And it's blue! There is a green one aswell.

We are attaching our logs. We have no previous Minecraft programming experience but we are keen to treat this as a learning opportunity (the elder member of our team has programming experience) but would appreciate any tips about how to set off in the right direction.

Gist with crash log here: https://gist.github.com/Fred-IGT/c3960019ad414a4f7791388556357ac2

**Comment by DonBruce64** [comment] 2020-01-12 18:58
This bug is a duplicate of #251.

**Closed** 2020-01-12 18:59 UTC
Labels: duplicate
