### ISSUE TITLE
Rotating parts from main model

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#272] opened 2020-01-18 02:00 UTC
So, as you may know, I’ve been working on industrial machinery lately, and I will have several tractors. Tho, I have my animated arms and stuff on the tractors, but I want the shovel part itself to be a different part that could be used in different vehicles, and have a selection of different shovel for my vehicles. But the issue I have, is making that part rotating, yes, it can rotate from a point defined in the part json itself but that’s the issue, different vehicles will require different rotating points, so defining that point in the part json will make that part only rotate from the same point regardless of the vehicle it’s on, so I would like to be able to define a rotation point for that part, but in the vehicle json and not the part json. Sadly my few experiences failed, and I want to have a true functional system for that.

**Comment by DonBruce64** [comment] 2020-01-18 16:06
What you're asking for is essentially retractable landing gear, as in both of them are moving parts.  That makes this ticket a duplicate of #261.

**Closed by DonBruce64** 2020-01-18 16:06 UTC
Labels: duplicate, enhancement
