### ISSUE TITLE
Crash when Leaving the Nether

### ISSUE THREAD

**Issue by Tampastrike** [DonBruce64/MinecraftTransportSimulator#889] opened 2021-08-05 21:26 UTC
[crash-2021-08-05_21.46.24-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6941710/crash-2021-08-05_21.46.24-server.txt)

This report is a crash experienced on a small private server.
So the crash began when I spawned the frame of the Ford Model A lookalike vehicle from the UNU pack, built an engine for it, installed the a flathead I6 into the vehicle. got in, forgot to fuel, refueled it and the second I accelerated, a crash occurred. The server removed the vehicle due to this, therefore I could rejoin. Upon rejoining, the vehicle workbench textures seem to come and go, they disappear, but the tables/benches are still accessible and I can see a complete interface when looking through the craft options. However, when I or anyone else goes into the nether, we are able to grab supplies and explore what we want, but when we decide to portal back, this crash report provided is the outcome before I even come out of the overworld loading screen.  

Also note that the mod works fine on singleplayer and vehicles are drivable, including the same vehicle with the same configuration that caused the first crash. Based on the mod list, are there any incompatible mods or could I have a corrupt download on my server file list? My theory was the vehicle that crashed the server initially may be respawning when the overworld begins to reload itself.

**Comment by DonBruce64** [comment] 2021-08-05 23:13
While this is a duplicate of an existing bug, I'm actually going to keep this one open and close the other one, as I haven't heard anything from the other user about a test build I gave them.  Plus, your issue is FAR more well-defined.  Would you be able to join our Discord and try the 20.0.3-BETA1 build?  And if it doesn't work, post a new crash report and latest.log in the chat?  I'll be able to cross-check that with the code and see what's up.

**Comment by Tampastrike** [comment] 2021-08-06 02:49
Absolutely, I can test the file on the server and repeat the steps for the crash.

**Comment by DonBruce64** [comment] 2021-08-07 20:36
Fixed in V20.0.3, nearly positive.

**Closed by DonBruce64** 2021-08-07 20:36 UTC
Labels: bug
