### ISSUE TITLE
Vehicles Causing Game Crashing

### ISSUE THREAD

**Issue by boeing717** [DonBruce64/MinecraftTransportSimulator#1053] opened 2022-01-11 19:20 UTC
I have not experienced this issue with any of the V19 versions.
When entering the drivers seat of any operable vehicle (any car pack) causes the game to crash. this happens in all of the most recent versions of V20.

here is what it tells me at first:

The game crashed whilst ticking entity
Error: java.lang.ArrayIndexOutOfBoundsException: -1
Exit Code: -1

I have used Vanillafix to see into it more, and says it is a MTS issue.

**Comment by DonBruce64** [comment] 2022-01-11 19:29
I will need a crash report to further look into this.

**Comment by boeing717** [comment] 2022-01-11 20:15
here you go

Time: 1/11/22 2:12 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: -1
	at org.lwjgl.input.JInputController.isButtonPressed(JInputController.java:191)
	at minecrafttransportsimulator.mcinterface.InterfaceInput.getJoystickButtonValue(InterfaceInput.java:286)
	at minecrafttransportsimulator.systems.ControlSystem$ControlsJoystick.isPressed(ControlSystem.java:682)
	at minecrafttransportsimulator.systems.ControlSystem.controlBrake(ControlSystem.java:126)
	at minecrafttransportsimulator.systems.ControlSystem.controlGroundVehicle(ControlSystem.java:382)
	at minecrafttransportsimulator.systems.ControlSystem.controlVehicle(ControlSystem.java:72)
	at minecrafttransportsimulator.entities.instances.AEntityVehicleB_Rideable.updateRider(AEntityVehicleB_Rideable.java:100)
	at minecrafttransportsimulator.entities.instances.EntityVehicleF_Physics.updateRider(EntityVehicleF_Physics.java:26)
	at minecrafttransportsimulator.mcinterface.BuilderEntityExisting.func_184232_k(BuilderEntityExisting.java:235)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2020)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461)
	at net.minecraft.client.entity.EntityPlayerSP.func_70098_U(EntityPlayerSP.java:1022)
	at net.minecraft.world.World.func_72866_a(World.java:1991)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72866_a(World.java:2056)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.input.JInputController.isButtonPressed(JInputController.java:191)
	at minecrafttransportsimulator.mcinterface.InterfaceInput.getJoystickButtonValue(InterfaceInput.java:286)
	at minecrafttransportsimulator.systems.ControlSystem$ControlsJoystick.isPressed(ControlSystem.java:682)
	at minecrafttransportsimulator.systems.ControlSystem.controlBrake(ControlSystem.java:126)
	at minecrafttransportsimulator.systems.ControlSystem.controlGroundVehicle(ControlSystem.java:382)
	at minecrafttransportsimulator.systems.ControlSystem.controlVehicle(ControlSystem.java:72)
	at minecrafttransportsimulator.entities.instances.AEntityVehicleB_Rideable.updateRider(AEntityVehicleB_Rideable.java:100)
	at minecrafttransportsimulator.entities.instances.EntityVehicleF_Physics.updateRider(EntityVehicleF_Physics.java:26)
	at minecrafttransportsimulator.mcinterface.BuilderEntityExisting.func_184232_k(BuilderEntityExisting.java:235)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2020)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
	at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461)
	at net.minecraft.client.entity.EntityPlayerSP.func_70098_U(EntityPlayerSP.java:1022)
	at net.minecraft.world.World.func_72866_a(World.java:1991)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72866_a(World.java:2056)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: mts:mts_entity (minecrafttransportsimulator.mcinterface.BuilderEntityExisting)
	Entity ID: 43
	Entity Name: entity.mts_entity.name
	Entity's Exact location: 378.34, 22.44, 506.81
	Entity's Block location: World: (378,22,506), Chunk: (at 10,1,10 in 23,31; contains blocks 368,0,496 to 383,255,511), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityPlayerSP['AugPinochet73'/41, l='MpServer', x=378.89, y=21.96, z=509.11]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Boeing172'/41, l='MpServer', x=378.89, y=21.96, z=509.11]]
	Chunk stats: MultiplayerChunkCache: 3249, 3249
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (796,4,-118), Chunk: (at 12,0,10 in 49,-8; contains blocks 784,0,-128 to 799,255,-113), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 20342044 game time, 15654 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 58 total; [EntityPlayerSP['AugPinochet73'/41, l='MpServer', x=378.89, y=21.96, z=509.11], BuilderEntityExisting['entity.mts_entity.name'/132, l='MpServer', x=332.25, y=21.15, z=317.75], EntityPainting['Painting'/157, l='MpServer', x=319.00, y=25.00, z=419.03], EntityPainting['Painting'/157, l='MpServer', x=319.00, y=25.00, z=419.03], EntityPainting['Painting'/170, l='MpServer', x=361.00, y=53.00, z=423.97], BuilderEntityExisting['entity.mts_entity.name'/43, l='MpServer', x=378.34, y=22.44, z=506.81], EntityPainting['Painting'/171, l='MpServer', x=355.03, y=52.50, z=424.50], EntityPainting['Painting'/172, l='MpServer', x=345.97, y=25.00, z=446.00], EntityPainting['Painting'/173, l='MpServer', x=362.00, y=34.50, z=544.03], EntityPainting['Painting'/174, l='MpServer', x=357.50, y=34.50, z=549.97], EntityPainting['Painting'/69, l='MpServer', x=268.00, y=30.50, z=363.03], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/2619, l='MpServer', x=378.89, y=23.04, z=509.94], BuilderEntityExisting['entity.mts_entity.name'/2620, l='MpServer', x=378.89, y=21.96, z=509.11], BuilderEntityExisting['entity.mts_entity.name'/66, l='MpServer', x=207.00, y=15.63, z=328.00], EntityPainting['Painting'/69, l='MpServer', x=268.00, y=30.50, z=363.03], EntityItemFrame['entity.ItemFrame.name'/70, l='MpServer', x=253.03, y=127.50, z=505.50], EntityItemFrame['entity.ItemFrame.name'/71, l='MpServer', x=253.03, y=127.50, z=503.50], EntityPainting['Painting'/81, l='MpServer', x=274.97, y=30.50, z=367.50], EntityItemFrame['entity.ItemFrame.name'/72, l='MpServer', x=253.03, y=126.50, z=503.50], EntityItemFrame['entity.ItemFrame.name'/73, l='MpServer', x=253.03, y=126.50, z=505.50], BuilderEntityExisting['entity.mts_entity.name'/74, l='MpServer', x=260.05, y=160.12, z=504.67], BuilderEntityExisting['entity.mts_entity.name'/203, l='MpServer', x=377.83, y=22.50, z=322.15], EntityItemFrame['entity.ItemFrame.name'/205, l='MpServer', x=399.50, y=8.50, z=368.97], EntityPainting['Painting'/173, l='MpServer', x=362.00, y=34.50, z=544.03], EntityItemFrame['entity.ItemFrame.name'/206, l='MpServer', x=399.50, y=9.50, z=368.97], EntityPainting['Painting'/174, l='MpServer', x=357.50, y=34.50, z=549.97], BuilderEntityExisting['entity.mts_entity.name'/207, l='MpServer', x=396.00, y=22.44, z=532.00], EntityPainting['Painting'/172, l='MpServer', x=345.97, y=25.00, z=446.00], BuilderEntityExisting['entity.mts_entity.name'/208, l='MpServer', x=378.00, y=21.22, z=551.00], EntityPainting['Painting'/81, l='MpServer', x=274.97, y=30.50, z=367.50], EntityPainting['Painting'/170, l='MpServer', x=361.00, y=53.00, z=423.97], EntityPainting['Painting'/171, l='MpServer', x=355.03, y=52.50, z=424.50], EntityBat['Bat'/83, l='MpServer', x=299.54, y=16.68, z=514.70], EntityItemFrame['entity.ItemFrame.name'/87, l='MpServer', x=281.50, y=127.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/88, l='MpServer', x=280.50, y=127.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/89, l='MpServer', x=279.50, y=127.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/90, l='MpServer', x=280.50, y=128.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/91, l='MpServer', x=281.50, y=128.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/92, l='MpServer', x=282.50, y=128.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/93, l='MpServer', x=281.50, y=129.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/94, l='MpServer', x=280.50, y=129.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/95, l='MpServer', x=282.50, y=129.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/96, l='MpServer', x=279.50, y=128.50, z=502.97], EntityItemFrame['entity.ItemFrame.name'/97, l='MpServer', x=279.50, y=129.50, z=502.97], EntityBat['Bat'/102, l='MpServer', x=301.34, y=22.06, z=498.41], EntityBat['Bat'/103, l='MpServer', x=302.40, y=17.70, z=508.10], EntityBat['Bat'/106, l='MpServer', x=301.88, y=15.16, z=511.28], EntityBat['Bat'/107, l='MpServer', x=303.02, y=18.26, z=509.09], EntityBat['Bat'/108, l='MpServer', x=299.67, y=15.12, z=508.23], EntityBat['Bat'/109, l='MpServer', x=299.49, y=17.77, z=508.84], BuilderEntityExisting['entity.mts_entity.name'/114, l='MpServer', x=315.00, y=22.44, z=272.00], BuilderEntityExisting['entity.mts_entity.name'/248, l='MpServer', x=416.33, y=22.65, z=272.80], BuilderEntityExisting['entity.mts_entity.name'/249, l='MpServer', x=431.94, y=22.54, z=314.23], EntityItemFrame['entity.ItemFrame.name'/250, l='MpServer', x=401.50, y=8.50, z=368.97], EntityItemFrame['entity.ItemFrame.name'/251, l='MpServer', x=400.50, y=8.50, z=368.97], EntityItemFrame['entity.ItemFrame.name'/252, l='MpServer', x=400.50, y=9.50, z=368.97], EntityItemFrame['entity.ItemFrame.name'/253, l='MpServer', x=401.50, y=9.50, z=368.97], EntityArmorStand['Armor Stand'/254, l='MpServer', x=407.50, y=32.06, z=525.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DonBruce64** [comment] 2022-01-11 20:47
Are you using a joystick currently?

**Comment by boeing717** [comment] 2022-01-11 20:58
yes. I have just figured that out now. everything works without it.

**Comment by DonBruce64** [comment] 2022-01-11 21:00
Ah, so your bug is the same as #1033.  There's a beta on Discord that will fix this issue.  I'm going to mark this as a duplicate of the other bug and close it.

**Closed by DonBruce64** 2022-01-11 21:00 UTC
Labels: bug, duplicate
