### ISSUE TITLE
Engine RPM not go down when engine off

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#942] opened 2021-09-12 01:31 UTC
https://user-images.githubusercontent.com/79125581/132967701-e0a771b5-eb78-4050-b6c1-590d00e82576.mp4

**Comment by boot2big** [comment] 2021-09-12 02:28
Something wrong must be happening with the LegacyCompats? There should be an extra variable that defines how quickly the engine should do this, and it seems that somewhere here it's being set to 0. Try adding this to your engine.
`"engineWinddownRate": 10,`
Alternatively, you can add to this number to make it go down quicker, or remove from it to make it go down slower.

**Comment by Naxgeneral** [comment] 2021-09-12 04:42
oh god i never noticed those value exist

**Comment by DonBruce64** [comment] 2021-09-12 14:43
Wait a second... @boot2big can you double-check if that value is *actually* set to 10?  Nax has a thing where he'll dump his JSON files into the export location and import them rather than work on the exported JSON.  So I *suspect* this issue is due to him copying over his older JSONs and then importing them.  And since those JSONs don't have the winddown, and not having something defaults to 0...  Well, that would make it 0.

**Comment by DonBruce64** [comment] 2021-09-12 14:44
@Naxgeneral same comment to you.  Does this happen because you're copying over a JSON that's missing that parameter?

**Comment by boot2big** [comment] 2021-09-12 15:02
> Well, that would make it 0.

 I do know that the code is there? It should be doing something. It very well could be the importing of older files though
![image](https://user-images.githubusercontent.com/53581325/132992627-b0da6d48-11cb-46b0-93bc-e4c9ddd8d1b0.png)

**Comment by DonBruce64** [comment] 2021-09-12 18:51
Yeah, I'm pretty sure the issue is the import of the older JSON.  But will wait to hear on Nax for this one before I mark as invalid.

**Comment by LauraDarkez** [comment] 2021-09-13 18:03
noticed this issue with other things too, but not so much that the engines wouldnt turn off at all, moreso that they would not wind down after being shut off, the sound would just cut out suddenly on the seagull variants if i turned off the engine. regardless of flying or sitting still

**Comment by boot2big** [comment] 2021-09-13 18:13
You'll need to add `"engineWinddownRate": 10,` to affected engines, tweak if you feel like it (lower is slower, higher is faster)

**Comment by DonBruce64** [comment] 2021-09-13 23:31
Again, I'm thinking that this is due to people who refuse to edit the exporter JSONs and instead edit their own copies and hot-load them into the game.  Will either wait on Nax for this for a week, or close it after then, whichever comes first.

**Closed** 2021-10-09 03:41 UTC
Labels: bug, invalid
