### ISSUE TITLE
[BUG] Model render thing is backwards?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#901] opened 2021-08-14 04:17 UTC
Maybe add a toggle to switch it back and forth if it's intentional? I think it'd be important for certain parts like tires/npcs/seats which I need to be at a specific angle for consistency

**Comment by DonBruce64** [comment] 2021-08-20 01:01
Which model thing is this?  The one in the dev-mode editor?

**Comment by boot2big** [comment] 2021-08-20 01:03
I can't run the build right now but might be able to in a bit. And yes, it's in the devmode editor. (The one with the OBJ, texture and position stuffs.)

**Comment by boot2big** [comment] 2021-08-20 07:34
Just tried using the latest build available on git, didn't seem to help

**Comment by DonBruce64** [comment] 2021-08-22 00:28
Okay, I see now what the issue is, and I KNOW I fixed it with this latest commit.

**Comment by DonBruce64** [comment] 2021-08-29 21:18
Fixed in V20.1.0.

**Closed by DonBruce64** 2021-08-29 21:18 UTC
Labels: bug
