### ISSUE TITLE
Overridemirror: true not working 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#197] opened 2019-10-12 13:07 UTC
I guess you understood, but it’s been a while that I kept having problems with overridemirror, lately while working with police vehicles and all those little leds parts around grills and windows, in the json of the car I made those leds overridemirror, in the game it just doesn’t change anything, like if there was no overridemirror lines… and the json line itself shouldn’t be wrong.
Help

**Comment by DonBruce64** [comment] 2019-10-13 14:37
Duplicate of #191.  Closing.

**Closed by DonBruce64** 2019-10-13 14:37 UTC
Labels: duplicate

**Comment by DonBruce64** [comment] 2019-10-15 23:28
Actually, this is an invalid ticket, not a duplicate.  User was un-aware of how overrideMirror functioned.
