### ISSUE TITLE
[bug] vehicles do not render when using replaymod after MTS v20

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#990] opened 2021-11-13 23:50 UTC
when you open a replay, all vehicles are invisible, including any parts.
You can still hear the sounds, and particles iirc

**Comment by DonBruce64** [comment] 2022-01-14 06:26
This will take a bit to fix.  Issue is ROB isn't following the player, so you don't get your queue to render vehicles.

**Comment by BraveCaperCat** [comment] 2022-03-17 16:04
Duplicate of ReplayMod/ReplayMod#675

**Comment by DonBruce64** [comment] 2022-04-22 00:39
Fixed in V21.2.0.

**Closed by DonBruce64** 2022-04-22 00:39 UTC
Labels: bug, backburner
