### ISSUE TITLE
Radio music not follow vehicle when active

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#932] opened 2021-09-02 05:47 UTC
Car radio used to play music in  you car while traveling but if your radio music not follow with your car?
this is _not spark joy_

**detail**: the radio sound not follow the vehicle and stayed at the position that radio activated

**Comment by 77RaZe77** [comment] 2021-09-03 08:22
I have the same problem as you

**Comment by boot2big** [comment] 2021-09-03 19:29
I can confirm this for several sounds, actually. If it isn't looping, it stays at its point of origin. If it _is_ looping, it follows it quite smoothly (like it did before)

**Comment by 77RaZe77** [comment] 2021-09-07 11:40
yes the problem is solved thanks a lot

**Comment by DonBruce64** [comment] 2021-09-19 23:26
Fixed in V20.2.0.

**Closed by DonBruce64** 2021-09-19 23:26 UTC
Labels: bug
