### ISSUE TITLE
Corvair & Beetle don't drive

### ISSUE THREAD

**Issue by thatoneF45fanatic** [DonBruce64/MinecraftTransportSimulator#1579] opened 2023-03-24 15:59 UTC
Hello. for some reason, when i try to drive the corvair or Beetle from Dr_prof_Luigi's Air-Cooled pack, they do not move. the engine revs, but the car doesn't move. i have done everything i can think of, but the issue's still not resolved. has anyone else reported this issue?

**Comment by DonBruce64** [comment] 2023-03-24 18:28
While this is more a UNU issue, I may be able to help.  Can you put in an engine from the Offical Content Pack and see if it works?  Also, do other vehicles such as those from the Offical Content Pack work with the engine you are using?

**Comment by thatoneF45fanatic** [comment] 2023-03-24 18:58
Well, the corvair's & Beetle's engine are exclusive to both of those vehicles, meaning they cannot be changed by another engine, or put in another vehicle.

**Comment by boot2big** [comment] 2023-03-24 20:14
It does appear to be caused by a customType on both the engine and vehicle, so I have to wonder if maybe keeping customTypes around truly was a good idea. On the other hand I can think of an up-to-date pack that still uses customTypes as well which would have to update nearly all of their custom parts to generic parts in order to accommodate their removal... 

This would perhaps be cause for a discussion between other pack authors as to how customTypes should be handled, if at all. Although I cannot participate for reasons that are irrelevant to this issue + an active break from Discord.

In the meantime I can offer a janky solution to you @theoneF45fanatic but be advised that this will involve 7zip and notepad to open the jar and edit a couple of JSONs.

**Comment by boot2big** [comment] 2023-03-24 20:21
Here's the guide on how to edit those JSONs.

Open Air-Cooled+Pack+[MTS]+1.10.2-14.0.0-1.0.1.jar in winrar, winzip, 7zip etc and navigate to /assets/mtsaircooled/jsondefs/parts, then select an engine to edit. (For demonstration purposes, why not mtsaircooled_part_vw_engine_40s.json?)

Open it in notepad (preferably notepad++ or an IDE editor if you're feeling fruity) and in the `general` section comment out or remove the `"customType" : "volkswagen",` line (comma and everything, otherwise the JSON will no longer load!) in order to tell MTS that this engine will no longer be customTyped and restricted to volkswagen slots.

Once you have finished with the engine JSON, navigate back out into the jsondefs section and enter the /vehicles directory instead, then edit the vehicle JSON. (For demonstration purposes we'll be fixing Herbie and not in the pet-like sense. That's no fun for anyone... mtsaircooled_vehicle_vw_type1_1969.json)

Scroll down to the parts section and at the bottom it should have the engines slot, this should have a part type of `engine_car` and a similar customType to the one you've just removed from the engine. Removing it here will unlock the vehicle to taking all engines within the minValue/maxValue size restraints (and of course you can lower/raise these to your heart's content while you're here anyways!)

Put the JSONs you've modified back into their appropriate locations in the .jar and close out the archive manager, then start up Minecraft again. The vehicle/engines you've modified should no longer be restricted.

**Comment by thatoneF45fanatic** [comment] 2023-03-24 21:53
I have found out that it isn't the engine which is causing the problem, it's the car itself.

**Comment by DonBruce64** [comment] 2023-03-24 22:58
I'm labeling this as a bug with the LCs, since this also borks the CAT pack.  I suspect it's related to linkedVariables.

**Comment by DonBruce64** [comment] 2023-03-26 01:59
Can confirm it's my issue, code is fixed, and you can grab a beta from Discord while you wait for an official release.

**Comment by thatoneF45fanatic** [comment] 2023-03-27 15:25
which discord?

**Comment by DonBruce64** [comment] 2023-03-29 01:22
I have it, just ping me.  I was going to ping you, but you don't appear to have the same name on there?

**Comment by thatoneF45fanatic** [comment] 2023-03-29 16:18
Well, my name on discord is 4449.

**Comment by DonBruce64** [comment] 2023-04-08 05:53
Addressed in 22.8.0.

**Closed by DonBruce64** 2023-04-08 05:53 UTC
Labels: bug
