### ISSUE TITLE
Tanker Trucks

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#85] opened 2019-01-20 23:32 UTC
It would be a lot like how the current fueling system works. There would be a loader/unloader (that could be toggled). Then if a vehicle has a tank (defined similar to fuel tank size) it can be filled via the loader/unloader. The only difference from the current fuel system is that it can be unloaded and the vehicle would need to keep track of the fluid ID.

It would be really cool if you could make this work with parts (kind of like a crate) so it could work with the Brigadier beds and UNU MCG

**Comment by DonBruce64** [comment] 2019-01-21 17:33
This issue is essentially a duplicate of #74, which asks for fuel-holding parts.  Please comment thoughts there.

**Closed by DonBruce64** 2019-01-21 17:33 UTC
Labels: duplicate, enhancement
