### ISSUE TITLE
Players sometimes don't stay in their seats on other clients in multiplayer when loading from data.

### ISSUE THREAD

**Issue by UTrosh** [DonBruce64/MinecraftTransportSimulator#1403] opened 2022-11-01 11:56 UTC
In multiplayer, the players are sometimes outside the vehicles but only visual, because for them they are indeed in the vehicle, I don't know how to explain but it's a visual bug, as soon as possible i share a video.

**Comment by DonBruce64** [comment] 2022-11-01 15:48
I've seen it.  This bug happens if you go to a person already in a vehicle, but does not happen if both of you are next to a vehicle, and then you both get in when close to one another, correct?

**Comment by boot2big** [comment] 2022-11-01 16:28
Correct. I've seen this bug myself and kept forgetting to report it. Note however that while the player isn't visually there, you can at times interact with them regardless (attacks mostly) as long as you know where in the vehicle they are.

**Comment by DonBruce64** [comment] 2022-11-01 19:09
The issue is down to some bug with how the client-side saved-rider-linking code is handled.  This causes the rider to be loaded on the server (and thus able to be hit if you know where they are), but for some reason this isn't translated to clients via the NBT data.  When you're right next to the player when they mount, you don't need the NBT data, as your client just gets the same "poot rider in car" packet that the actual rider got.  It's only when they're in the seat and you go into that chunk and start loading the vehicle that something is borked and makes them not mount.  It's just been such a low priority because the bug is fairly minor that I haven't fixed it yet.

**Comment by DonBruce64** [comment] 2022-12-13 03:34
Fixed in 22.5.0.

**Closed by DonBruce64** 2022-12-13 03:34 UTC
Labels: bug
