### ISSUE TITLE
Phantom Hitbox Issue

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1545] opened 2023-02-25 02:56 UTC
When the boom truck is used, there are phantom collisions from what I assume to be hitboxes from the boom. Unfortunately I can't really provide any more information that this video:

https://user-images.githubusercontent.com/36775575/221332522-dfaf2e53-d3f8-4391-b79e-fc401f88f1af.mp4

I think it has something do do with the applyAfter since it does not happen when the boom is stowed (no animations), and in the past there were related hitbox problems (#1031)

**Comment by DonBruce64** [comment] 2023-02-25 16:06
If you re-load the world, does the boom end up in the spot where the phantom hitboxes are?  I saw some oddities with variables not updating in the past.  Wonder if that's what this is.

**Comment by DrprofLuigi** [comment] 2023-02-25 22:24
I haven't really been able to recreate the issue, but I think that when I reloaded the phantom hitboxes disappeared (or re-synced with the boom), I don't remember the boom model moving unexpectedly.

**Comment by DonBruce64** [comment] 2023-02-28 02:06
Closing then since cannot reproduce.

**Closed by DonBruce64** 2023-02-28 02:06 UTC
Labels: bug, invalid
