### ISSUE TITLE
[Bug] Client Crashing when trying to start a plane or adding an instrument

### ISSUE THREAD

**Issue by pierreborde** [DonBruce64/MinecraftTransportSimulator#365] opened 2020-03-25 14:33 UTC
The title sums up the thing. W've been trying to build planes on multiplayers but we can't get them working. Everyone has the mod installed on client side and the same files (Skeleton and vehicles) are on server side. I attached what the server says when people are disconnected. After few try in creative, seems that it does the same with all the panes, either we can't get a start or attach instruments.
[message.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4381515/message.txt)

**Comment by DonBruce64** [comment] 2020-03-25 20:33
This is a duplicate of #354. Update your version of MTS to the most recent (V17.3.1) and the error will go away.

**Closed by DonBruce64** 2020-03-25 20:33 UTC
Labels: duplicate

**Comment by pierreborde** [comment] 2020-03-26 13:41
Alright, thanks for the fast update about the problem. I saw the duplicate label, sorry the time wasted, didn't know about the "Closed" section. Love the mod and thanks for the hard work !
