### ISSUE TITLE
[BALDI] Wheel height averages out between two wheels

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#657] opened 2020-12-13 05:38 UTC
Seems to pick both the highest, and lowest wheel, and averages the height out between them...
![image](https://user-images.githubusercontent.com/53581325/102004077-8150e980-3cdb-11eb-878a-20a8c7b9d4eb.png)

**Comment by DonBruce64** [comment] 2020-12-13 06:00
This is as designed.  So this isn't bad math.  Rather, it's a request to change how the math is performed.  Flagging it as an enhancement.

**Comment by fsendventd** [comment] 2020-12-14 19:31
Shouldn't this be changed so that it uses the X and Z of the lowest-contacting box as well?

**Comment by DonBruce64** [comment] 2020-12-14 19:46
That would be bad, as then you'd get inconsistent XZ coordinates for vehicles with dual-axle rear wheels.  The ideal space for them would be to average the two rear wheels and set the position for checks to the middle of them.  If you chose the lowest wheel, and all the wheels are the same height, then you'll just end up picking randomly.  That could lead to the left and right boxes being in different positions and would lead to funky handling.

**Comment by fsendventd** [comment] 2020-12-18 19:00
> 
> 
> That would be bad, as then you'd get inconsistent XZ coordinates for vehicles with dual-axle rear wheels. The ideal space for them would be to average the two rear wheels and set the position for checks to the middle of them. If you chose the lowest wheel, and all the wheels are the same height, then you'll just end up picking randomly. That could lead to the left and right boxes being in different positions and would lead to funky handling.

Couldn't a sort of system be added so that if they're all at the same height it picks the rearmost one or something?

**Comment by DonBruce64** [comment] 2020-12-19 01:07
But why would you want something like that?  If you have two wheels close together, you'd want to take them both into account, not just ignore the front ones.  If that's the case, why bother having those front wheels anyways?

**Comment by fsendventd** [comment] 2020-12-22 19:48
> 
> 
> But why would you want something like that? If you have two wheels close together, you'd want to take them both into account, not just ignore the front ones. If that's the case, why bother having those front wheels anyways?

Think about it. If a trailer with two axles is rotated, it'll rotate around the lowermost axle. If the front axle comes off the ground then it should fall down due to physics, rotating the trailer, which then brings it below the rear one and would allow it to be used for calculations. I just don't think averaging the wheel positions is a good idea, mostly for vehicles with many wheels like wheeled tank destroyers (Sd.Kfz.234, B1 Centauro, Stryker, Rooikat) or large cargo aircraft (C-5 Galaxy, A380, An-225, Me 323).

**Comment by DonBruce64** [comment] 2020-12-23 01:32
True, but the same could be said for wanting to use the front wheels, as if the trailer is going backwards up a hill, then you wouldn't want to use the rear wheels.

**Comment by DonBruce64** [comment] 2020-12-24 04:44
Marking this fixed as of V19.12.0, as the ticket was for Y-value averaging.  If we run into issues with other averaging systems, we can check those.

**Closed by DonBruce64** 2020-12-24 04:44 UTC
Labels: enhancement
