### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by MikcaelX** [DonBruce64/MinecraftTransportSimulator#1078] opened 2022-01-28 21:24 UTC
Hi, I've a problem with my minecraft when I try to use the mod, 
all of the text of the mod look like that : 
![image](https://user-images.githubusercontent.com/67520160/151623313-1a4eb64b-f778-415c-9091-e2e01f73573c.png)
![image](https://user-images.githubusercontent.com/67520160/151623355-9404e921-67ec-4bac-a2ba-caa6bad462a6.png)

And that unreadable :/ 
So, do someone know how do I fix that ? Thanks !

**Comment by DonBruce64** [comment] 2022-01-29 04:14
Check existing issues before posting new ones.  (Duplicate of #1048 )

**Closed by DonBruce64** 2022-01-29 04:14 UTC
Labels: invalid

**Comment by MikcaelX** [comment] 2022-01-29 13:25
My bad, thank you !
