### ISSUE TITLE
Traffic Cones Crash Game

### ISSUE THREAD

**Issue by TrafficAhead** [DonBruce64/MinecraftTransportSimulator#300] opened 2020-02-09 16:57 UTC
I'm not sure about too much on this issue, but basically I entered territory where Traffic Cones were and the game immediately crashes from that point on. I don't know if this is client based or server based, but my friend said he also crashed in the same place. We had to downgrade from V16 to V15.10. Crash report is available upon request if needed.

**Comment by DonBruce64** [comment] 2020-02-10 14:49
Yup, I'm going to need a crash report to figure anything out about that.  I placed down some decor in testing builds without issue, so not sure what the issue is.

**Comment by TrafficAhead** [comment] 2020-02-10 22:20
Right, here you go. Tried to cut most unneeded stuff, don't know if I cut important stuff or not but /shrug
[crashcones.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4183340/crashcones.txt)

**Comment by DonBruce64** [comment] 2020-02-10 22:28
Yup, that's a cone crash on my end for sure.  Will look into it and fix.

**Comment by DonBruce64** [comment] 2020-02-23 03:43
Fixed in V16.1.0.

**Closed by DonBruce64** 2020-02-23 03:43 UTC
Labels: bug
