### ISSUE TITLE
[Bug] scaling only applying duration and proper direction in y axis

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1318] opened 2022-09-05 22:24 UTC
scaling issues if y axis value = 0

![image](https://user-images.githubusercontent.com/53153740/188517223-ec7140da-aaf5-48b8-9777-faead277b68c.png)

**Comment by DonBruce64** [comment] 2022-09-05 23:34
Duplicate of #1316

**Closed by DonBruce64** 2022-09-05 23:34 UTC
Labels: bug, duplicate
