### ISSUE TITLE
Vehicles move very slowly despite not doing so before

### ISSUE THREAD

**Issue by DiamondNinja109** [DonBruce64/MinecraftTransportSimulator#44] opened 2018-11-18 22:32 UTC
This happens with every vehicle, but when I accelerate, the wheels turn quickly as before but the vehicle moves like a snail. I am using Official Pack V8 and Minecraft Transport Simulator-1.12.2-12.2.0.jar, and this happened just after I installed these newer versions today.

**Comment by DonBruce64** [comment] 2018-11-19 01:30
Does this happen with a newly-placed vehicle?  Or are these existing vehicles?

**Comment by DiamondNinja109** [comment] 2018-11-19 23:08
This happens with both newly-placed vehicles and existing vehicles.

**Comment by DiamondNinja109** [comment] 2018-11-19 23:08
I will have to make a video and link it here:

**Comment by DonBruce64** [comment] 2018-11-25 22:39
Currently working on this in Discord to determine the issue.  Appears to be a mod conflict of some sort on user's world.

**Comment by DonBruce64** [comment] 2018-12-11 04:04
Couldn't get a response from user, and the video that he posted has been removed.  Additionally, user said that he couldn't get the bug to reproduce on a new world.  Encountered a similar issue during a dev test, which happened as follows:

Was in the Firetruck and gunned it in first gear.  Before the wheels could catch, I shifted up.  Must've been in the right powerband, because I made it all the way up to the final gear without regaining traction.  I suspect this is what the user experienced, just they had particles turned off so they didn't see the smoking tires.  No way to confirm this as neither one of us have been able to reproduce the exact issue, so closing as invalid as there is no known issue to fix.

**Closed by DonBruce64** 2018-12-11 04:04 UTC
Labels: bug, invalid
