### ISSUE TITLE
[Bug] Crazy shading&texture transparency bug with Official Vehicles

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#254] opened 2020-01-06 11:45 UTC
In some cases some vehicles from Official pack have transparent textures or overshading problems.
![InkedUntitled_1 4 1_LI](https://user-images.githubusercontent.com/43516901/71816266-03dd2c00-30bd-11ea-8e4e-1716703b6951.jpg)

**Comment by DonBruce64** [comment] 2020-01-08 21:27
Odd, is it only OCP vehicles that have this issue?

**Comment by StarterCraft** [comment] 2020-01-09 13:34
Yes. This problem has appeared before [this](https://github.com/DonBruce64/MinecraftTransportSimulator/issues/247) issue has appeared. First, I turned on the shaders and saw this Scout's textures' bug. Later I have lost any ability to turn on the shaders in any world having any IV vehicles. I think these problems are interrelated. I think it's worth checking out. I can also offer you files .log of that day. It might also help the bugs' investigation.

**Comment by DonBruce64** [comment] 2020-01-11 22:43
The shaders crash you referenced is due to a fix I implemented to prevent odd sound corruption and flashing vehicles referenced in #169.  If the OCP vehicles had this issue before that, it must be due to something in my rendering routine that only affects OCP vehicles.  Likely something due to transparency or something.  Will have to investigate.  Can you tell me what shaders/version cause this so I can reproduce it on my end?

**Comment by StarterCraft** [comment] 2020-01-13 10:51
Any shaders cause the case. You can use the YouTubers' Dream Shaders [download link](https://www.planetminecraft.com/texture_pack/youtuber-dream-shaders/).

**Comment by StarterCraft** [comment] 2020-02-17 04:41
@DonBruce64, New info about this issue! OCP Vulcanair has texture transparency while taxiing with shaders turned on.
![2020-02-17_11 52 21](https://user-images.githubusercontent.com/43516901/74623793-f5386900-5180-11ea-8802-42516c8581cc.png)
![2020-02-17_11 52 17](https://user-images.githubusercontent.com/43516901/74623798-f9fd1d00-5180-11ea-8448-b38dcbf8855d.png)

**Comment by DonBruce64** [comment] 2020-02-18 00:53
Again "Can you tell me what shaders/version cause this so I can reproduce it on my end?"  Showing me a picture of a bug won't help if I don't know your *exact* configuration.

**Comment by StarterCraft** [comment] 2020-02-19 08:30
@DonBruce64, Again: "Any shaders cause the case. You can use the YouTubers' Dream Shaders or the TME Shaders."

**Comment by DonBruce64** [comment] 2020-02-19 16:14
Whoops.  Sorry about that.  Didn't see that....

**Comment by DonBruce64** [comment] 2020-04-17 04:37
So in V18.0.0, I made numerous changes to make the lights better.  Next cycle will address other shaders issues with rendering the main vehicle model.

**Comment by DonBruce64** [comment] 2020-07-04 04:23
So I made a bunch of changes to the rendering as of late.  @StarterCraft, you able to test on V18.4.0?

**Comment by StarterCraft** [comment] 2020-07-08 09:27
Ok, I'll do that.

сб, 4 июл. 2020 г. в 12:23, DonBruce64 <notifications@github.com>:

**Comment by DonBruce64** [comment] 2020-09-18 23:25
Same comment about V19.0.0.  I've completely re-done the rendering system in that version, so I don't see any reason why vehicles would be holographic in that version.

**Comment by DonBruce64** [comment] 2020-10-10 22:24
Realized I might have to ping you @StarterCraft

**Comment by StarterCraft** [comment] 2020-10-12 08:38
Hi @DonBruce64! Sadly, I had no time to update my instance of IV this month, so I have not tested the update.

**Comment by DonBruce64** [comment] 2020-10-12 20:54
@StarterCraft No worries.  Whenever you get a chance let me know.  Trying to wrap up all my tickets before I try to put to newer MC versions.

**Comment by DonBruce64** [comment] 2021-07-29 03:33
Fixed in V20.0.0.

**Closed by DonBruce64** 2021-07-29 03:33 UTC
Labels: bug
