### ISSUE TITLE
[Bug] Flying player arms and legs

### ISSUE THREAD

**Issue by Supertheobrg** [DonBruce64/MinecraftTransportSimulator#728] opened 2021-03-05 11:04 UTC
plz help I use on server whit plugin and mods
![Minecraft_1 12 2_19_02_2021_19_06_31](https://user-images.githubusercontent.com/68150571/110107205-e4b65900-7daa-11eb-82eb-f7be1ad519f0.png)
Mods list :
![image](https://user-images.githubusercontent.com/68150571/110107383-17f8e800-7dab-11eb-9acf-f982ce141a32.png)

**Comment by DonBruce64** [comment] 2021-03-05 15:52
Could you join the Discord and try one of the betas we have available to see if this fixes the issue?

**Comment by Supertheobrg** [comment] 2021-03-05 16:26
> Pourriez-vous rejoindre Discord et essayer l'une des versions bêta dont nous disposons pour voir si cela résout le problème?

Yes of course

**Comment by DonBruce64** [comment] 2021-03-06 01:45
So, it turns out this is a duplicate of #700.  Closing as such.

**Closed by DonBruce64** 2021-03-06 01:45 UTC
Labels: bug, duplicate
