### ISSUE TITLE
Crash while installing a aircraft wheel

### ISSUE THREAD

**Issue by HydrogenC** [DonBruce64/MinecraftTransportSimulator#220] opened 2019-11-24 01:04 UTC
I installed the latest version of IV and Golden Airport Pack, and as met the problem as the title explained. 
[crash-2019-11-24_08.59.55-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/3883108/crash-2019-11-24_08.59.55-client.txt)

**Comment by DonBruce64** [comment] 2019-11-24 17:50
Going to need more information to know why this is happening.

1) What vehicle were you putting the wheel on?
2) What wheel were you attempting to put on?
3) Were you on a server, or in Singleplayer?
4) Does the same issue happen if you remove all other mods besides IV?

**Comment by ChlorineX** [comment] 2019-11-25 11:09
The CRJ700 in Golden Airport Pack
Small aircraft wheel in UNU Parts Pack
Singleplayer
Yes, I attempted to install only IV and its packs, this bug also occurs. Also, the bug doesn’t occur every time, it occurs occasionally, I would have to try several times to make it reproduce.

**Comment by DonBruce64** [comment] 2019-11-25 20:54
Interesting.  Is this in creative mode or survival?

**Comment by ChlorineX** [comment] 2019-11-26 11:31
Creative

**Comment by DonBruce64** [comment] 2019-11-26 21:32
Very odd.  This crash is on the client, and indicates that "air" was put on the vehicle on the server, because only if a valid part is put on the vehicle does this packet get sent.  You wouldn't be able to do the same crash with only MTS, and then post the crash and the log, would you?  If I'm getting any unchecked exceptions I should be able to see those in the log and they'll help me track down the issue quicker.

**Comment by HydrogenC** [comment] 2019-11-30 05:55
I have just did some tests to reveal the cause of this bug. It seems that the crash is because that two slots are very close so that both of them are clicked at a time and this causes the bug.

**Comment by HydrogenC** [comment] 2019-11-30 06:00
Example: 
![2019-11-30_13 59 06](https://user-images.githubusercontent.com/33123710/69896366-acd78f00-1379-11ea-8d7c-8f21c82d88c3.png)
These two crate slots are very close to each other. If I click this way, both of them would respond to my click at a time, and that's the cause of the crash.

**Comment by HydrogenC** [comment] 2019-11-30 06:27
I have confirmed that the cause of this mod is caused by the reasons above. 
Now I am able to elaborate the cause of the bug. 
For example: 
1. Two wheel slots are so close to each other that if I click on one of them, the other one will also be clicked on. 
2. I have one wheel on my hand, and I clicked on the green cube. 
3. Both slots are detected to be clicked, and both of them intended to subtract one wheel from my inventory, but I've got only one. -> boom, crash!

**Comment by DonBruce64** [comment] 2019-11-30 19:42
See, that statement would make sense, *except* for this point: "and both of them intended to subtract one wheel from my inventory, but I've got only one".  The only time the system removes items from an inventory is survival mode, and you told me earlier you were in creative.  That being said, your screenshot shows survival.  Need to know which modes this occurs in to be sure I know what the issue is.

**Comment by HydrogenC** [comment] 2019-12-01 00:33
> See, that statement would make sense, _except_ for this point: "and both of them intended to subtract one wheel from my inventory, but I've got only one". The only time the system removes items from an inventory is survival mode, and you told me earlier you were in creative. That being said, your screenshot shows survival. Need to know which modes this occurs in to be sure I know what the issue is.

Actually survival, I misstated before.

**Comment by DonBruce64** [comment] 2019-12-01 02:49
Ah, in that case I know exactly where the issue is.  Will do my best to fix in the next update.

**Comment by HydrogenC** [comment] 2019-12-01 04:17
Thanks very much

**Comment by DonBruce64** [comment] 2019-12-07 03:01
Fixed in V15.6.0.

**Closed by DonBruce64** 2019-12-07 03:01 UTC
Labels: bug
