### ISSUE TITLE
Rendering Entity Null on other Player in Vechile

### ISSUE THREAD

**Issue by kandivia** [DonBruce64/MinecraftTransportSimulator#26] opened 2018-10-27 02:03 UTC
On a server, while a player is mounted in a vehicle, if another player walks into render distance of it, they receive a null pointer exception and crashes their client.

**Comment by DonBruce64** [comment] 2018-10-27 02:05
This is caused by the client not getting the vehicle data from the server before the player starts to render.  There's a delay in Minecraft between the basic entity data, and the supplemental data that MTS sends.  Will patch.

**Comment by DonBruce64** [comment] 2018-11-15 03:41
Fixed in Commit 3436ec1a4678eed39c85bd1848c6d4362930c796.

**Closed by DonBruce64** 2018-11-15 03:41 UTC
Labels: bug
