### ISSUE TITLE
[PACKARD] Scout and Trimotor have rogue skins

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#868] opened 2021-07-10 21:07 UTC
Skins will persist whether MTS loads their json or not. (Obviously the texture will remain missing though)

**Comment by DonBruce64** [comment] 2021-07-13 04:13
I get why this would happen for vehicles, but are you sure the items are still there?  Cause I don't see how the items would exist as those are created for each skin.

**Comment by boot2big** [comment] 2021-07-13 04:34
Seeing as how the Tormador skin I made popped up on Trin after many versions of being deleted, as well as a certain offensive Scout skin, both still exist... yeah, they do

**Comment by DonBruce64** [comment] 2021-07-14 04:10
Sure, they appear on the vehicle.  But how the heck do you get those vehicles as items is what I'm confused about.  You shouldn't be able to wrench them and get them in item form because the skin def wouldn't have even loaded when the item generator was queried.

**Comment by boot2big** [comment] 2021-07-14 05:30
I mean... load the newest trin and IVV? Or modify any pack that adds skins to remove them? I know for a fact that the IVV V1.5 beta has no scout skin but I can still spawn the military scout (albeit with no texture) and pick it back up

**Comment by DonBruce64** [comment] 2021-07-16 13:09
Found out today that it's the fault of the OCP for including the definition internally.  Likely I did a JSON export with IVV installed and that definition got applied in there.  Same for the MAI Trimotor.  Will fix.

**Comment by boot2big** [comment] 2021-07-27 03:15
Perhaps this is still a bug then, as the LC/DevMode thing is exporting external skins along with the normal defined ones?
It might be too tricky to fix if I recall correctly as to how external skins actually get parsed but still, a bug?

**Comment by DonBruce64** [comment] 2021-07-27 03:26
It is but is isn't.  The problem is the way the parser works.  It goes and loads all pack items and skins into two different data registers.  Then when all packs have been parsed, it goes and adds the skins into the JSON of any valid items.  So then as far as IV is concerned, the skins are just additional definitions with textures, but the textures are in the added jar rather than the core pack.  However, because they're just additional definitions, they're then part of the main JSON and get exported with that item in dev mode.  I don't have a good way to parse that out as to do that I'd have to remove the definition, which would break the JSON that's loaded if that definition was currently in-use in the world.

**Comment by DonBruce64** [comment] 2021-09-19 23:23
Fixed in V22.

**Closed by DonBruce64** 2021-09-19 23:23 UTC
Labels: bug, packard
