### ISSUE TITLE
Engine that is crafted from Engine Hoist have chances of being bugged

### ISSUE THREAD

**Issue by Linux-MissingNo** [DonBruce64/MinecraftTransportSimulator#304] opened 2020-02-11 19:51 UTC
Copy pasted from https://github.com/ProsperCraft/towncraft/issues/39

Summary: Engines crafted from Engine Hoist have chances of being bugged. When you attempt to fill them with the required fuel, it will not accept the fuel as if it was the wrong fuel.

Steps to reproduce:
 
   1. Craft the engine. (You may have to repeat this step a lot).
   2. Once you get the bugged engine, put it in a vehicle and then try to fuel with a pump. (You should not be able to fuel it.)
   3. Attempt to start the engine. You should be crashing on this step.

Expected result: being able to fuel the engine and empty engine should be not crashing

Actual result: engine cannot be fuelled and will crash the server if it is started

Note: ~~Trin pack have this issue and I have not yet confirmed if other packs have this issue.~~ OddlySeagull said this is an issue with the core and not with his pack
Note: This bug occurred in Towncraft 1.12.2 version 4.4, I had not confirmed it in a clean environment.

Note 2: Trin part pack: 2.8.0, Trin civil pack 2.5.0, Immersive Vehicles-1.12.2-15.10.0
Crash log for when starting an empty bugged engine: https://paste.dimdev.org/mokavovaso.mccrash

**Comment by Linux-MissingNo** [comment] 2020-02-11 20:37
New: Trin pack may be entirely responsible for this. I don't want to bring false hope just yet. 
version for these packs: Trin part pack: 2.8.0, Trin civil pack 2.5.0(Will be added in the post above)

**Comment by TheOddlySeagull** [comment] 2020-02-12 11:55
I have literally no idea on what could cause that. Never had any issues with my engines, all my sounds should work fine, and my engine jsons should all be correct. I am unable to reproduce it. Is there a specific engine you tested that on?

**Comment by DecafMegalodon** [comment] 2020-02-21 01:11
He apparently tested it on a humvee with a v12 turbo engine. This is the same bug as #315 which has a crash log from the server owner

**Comment by DonBruce64** [comment] 2020-02-22 19:52
Closing this bug as it's a duplicate and there's more information in #315.

**Closed by DonBruce64** 2020-02-22 19:52 UTC
Labels: bug, duplicate
