### ISSUE TITLE
Motorcycle steering/angled "turnsWithSteer" axis

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#400] opened 2020-04-20 22:58 UTC
for adding support with motorcycles and vehicles with angled steering, allow for "rot" : [ , , ] to effect the angle of the steering axis on wheels, as currently the wheels that turn with steering can only rotate on y-axis.

**Comment by DonBruce64** [comment] 2020-04-21 00:47
I'm going to table this for the moment until I get a chance to mess with rotations.  Rotating wheels is hard-coded and nasty.

**Comment by DonBruce64** [comment] 2020-06-20 00:52
So I just realized this is technically an invalid ticket, as the feature already exists.  However, it's also currently bugged, as per ticket #374.  Marking as invalid, but will fix the root cause of the issue too.

**Closed by DonBruce64** 2020-06-20 00:52 UTC
Labels: enhancement, invalid
