### ISSUE TITLE
Bug in  Immersive Vehicles-1.12.2-20.0.1

### ISSUE THREAD

**Issue by Supertheobrg** [DonBruce64/MinecraftTransportSimulator#886] opened 2021-07-30 09:57 UTC
Hello my serveur crash when A player join the game
[crash-2021-07-30_11.44.21-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6906726/crash-2021-07-30_11.44.21-server.txt)
[crash-2021-07-30_11.38.48-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6906728/crash-2021-07-30_11.38.48-server.txt)

**Comment by DonBruce64** [comment] 2021-07-31 03:46
Odd, does this happen all the time?  Does it only happen with some players?  I'm not quite sure how this crash could happen.  Would you be able to join the Discord and ping me so I can give you some betas to test and try and figure out why this is happening?

**Comment by DonBruce64** [comment] 2021-08-05 23:13
Closing as dupe of #889 due to no user response but the same crash report in that bug.  New ticket has more information.

**Closed by DonBruce64** 2021-08-05 23:13 UTC
Labels: bug, duplicate
