### ISSUE TITLE
Custom variables with the same name don't merge buttons

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1029] opened 2021-12-27 07:00 UTC
If a part and a vehicle share a custom variable, two buttons appear instead of just one. If you flip one, the other is flipped in unision.

![image](https://user-images.githubusercontent.com/36775575/147444101-8333c98c-33f6-40c2-8743-e981ad4572d5.png)

**Comment by DonBruce64** [comment] 2022-01-02 05:27
Duplicate of #1024

**Closed by DonBruce64** 2022-01-02 05:27 UTC
Labels: bug, duplicate
