### ISSUE TITLE
Connections with parts glitch out

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#832] opened 2021-05-31 19:54 UTC
When I try to connect a vehicle to another vehicle's part, the vehicle placed first disappears, and the towed vehicle (if it doesn't disappear) flings off in the direction of the connection.

Steps to replicate:
Download the [UNU DEV](https://www.dropbox.com/sh/5d3qoj6hr8g0u4w/AACRJF3WUTf-23H_ziZ6cYAUa?dl=0)
Place the UNU Crane Mule and UNU Wolf
Extend the crane's boom with the middle lever on the side
Park the UNU Wolf under the hook
Connect to the hook from the Wolf

All vehicles involved use the new V20 connection system, and I tried this on a few Betas up to 37

Videos:
https://cdn.discordapp.com/attachments/777610390129344522/848497048155717632/2021-05-30_02-41-43.mp4
https://cdn.discordapp.com/attachments/777610390129344522/848497051976728586/2021-05-30_02-42-32.mp4
https://cdn.discordapp.com/attachments/551893809420697603/848497709651722280/2021-05-30_02-46-13.mp4

**Comment by DonBruce64** [comment] 2021-06-06 00:33
Tried this and couldn't re-produce the issue.  However, I also wasn't able to connect the trailer in the first place because there was a missing JSON parameter that was causing the game to crash.  Once that was fixed, everything worked fine.  Closing this ticket as it's both a beta issue, and not reproducible in the most current beta.

**Closed by DonBruce64** 2021-06-06 00:33 UTC
Labels: bug, invalid
