### ISSUE TITLE
[Suggestion] Farming Equipment

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#226] opened 2019-12-11 02:04 UTC
Farming equipment would add a cheaper way for large scale farming in survival. Three new parts/trailer types would be added. The First being a plow, which would till the land equivalent to the width of the trailer. The second would be for spreading seeds, and another for hydrating. A new part would be created for a harvesting tool, which would collect the seeds and food items.

**Comment by DonBruce64** [comment] 2019-12-11 02:15
Duplicate of #154.  You're even in that thread talking about farm equipment...

**Closed by DonBruce64** 2019-12-11 02:15 UTC
Labels: duplicate, enhancement
