### ISSUE TITLE
The game fails to launch

### ISSUE THREAD

**Issue by LasthopeBR** [DonBruce64/MinecraftTransportSimulator#1414] opened 2022-11-07 04:12 UTC
Whenever I try to launch the game, this message is displayed in the latest.log:

[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9948067/latest.log)

https://mclo.gs/G6PXwpw

**Comment by DonBruce64** [comment] 2022-11-07 21:58
Dassa nother @Elephant1214 issue.  Related to #1402 probably.

**Comment by Elephant1214** [comment] 2022-11-07 22:03
It only happens with SecurityCraft, technically a duplicate of that other ticket. Send the log in that issue just to track it.

**Comment by Elephant1214** [comment] 2022-11-07 23:28
Scratch that, doesn't seem to be the issue

**Comment by Elephant1214** [comment] 2022-11-07 23:29
Can you Try without Security Craft just to be sure?

**Comment by Elephant1214** [comment] 2022-11-14 00:50
I need the crash report, the partial log that you sent doesn't seem to contain everything.

**Comment by DonBruce64** [comment] 2022-12-03 03:36
Fixed in 22.4.0.

**Closed by DonBruce64** 2022-12-03 03:36 UTC
Labels: bug
