### ISSUE TITLE
[BUG] Seats issue with orientation, vehicle facing direction and handheld guns

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1343] opened 2022-09-29 13:16 UTC
![image](https://user-images.githubusercontent.com/53153740/193041355-42ad598e-c3a0-4ad4-970c-06ab49cac50e.png)
![image](https://user-images.githubusercontent.com/53153740/193041540-39ef5854-ebaa-4ad4-8e2f-c1cf9d142611.png)

**Comment by DonBruce64** [comment] 2022-10-02 20:02
I doubt I can fix the flipping, as that's due to the Quaternion interpolation that's fixed all the existing issues, and I don't wanna poke it if the issue is just you moving your head too far and MC freaking out a tad.  But the gun aiming?  That's a thing that should be a problem and I can hopefully fix.

**Comment by DonBruce64** [comment] 2022-10-02 22:35
Fixed in V22.2.0.

**Closed by DonBruce64** 2022-10-02 22:35 UTC
Labels: bug
