### ISSUE TITLE
[enhancement] Snap and override connection

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1362] opened 2022-10-11 14:15 UTC
two additions to the current connections system
-snap - When two compatible connection points with this set to true move towards eachother and are within the valid distance they will automatically connect to eachother
-Override - when a connection with override set to true is connected it will cancel all other connections. Useful for stuff like cranes, forklifts that should be able to automatically uncouple a vehicle, in this case a container or pallet from the vehicle they are connected to

**Comment by DonBruce64** [comment] 2022-10-12 05:26
Ya get one thing per ticket sir.  Pick your position.

**Comment by Ilya-torshov** [comment] 2022-10-12 23:21
snappy boi

**Comment by DonBruce64** [comment] 2022-10-15 06:44
Congrats, that makes this ticket a duplicate of #1348 !

**Closed by DonBruce64** 2022-10-15 06:44 UTC
Labels: duplicate, enhancement
